esphome:
  name: levoit-classic-300s-ci
  friendly_name: Levoit Classic 300S CI

esp32:
  variant: esp32
  flash_size: 4MB
  cpu_frequency: 160MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

external_components:
  - source:
      type: local
      path: components
    components: [levoit_classic_300s]

logger:
  level: DEBUG
  baud_rate: 0

uart:
  id: humidifier_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

levoit_classic_300s:
  uart_id: humidifier_uart
  update_interval: 30s
  command_interval: 100ms
  status_response_timeout: 5s
  humidifier:
    name: Humidifier
  mode:
    name: Mode
  target_humidity:
    name: Target humidity
  manual_mist_level:
    name: Manual mist level
  night_light:
    name: Night light
    gamma_correct: 1.0
    default_transition_length: 0s
  current_humidity:
    name: Current humidity
  temperature:
    name: Temperature
  tank_lifted:
    name: Tank lifted
  no_water:
    name: No water
  communication_problem:
    name: MCU communication problem
  raw_status:
    name: Raw MCU status
